name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go module
      run: go mod init test && go mod tidy
      
    - name: Test
      run: go test
      
    - name: Build
      run: go build
      
    - name: install binary
      run: go install
